---
title: "Plots together"
output: html_document
---

Combine plots together:

```{r}
rm(list = ls())
load('results/df_cc.Rdata')
load('results/df_qtrait.Rdata')
load('results/rf_cc.Rdata')
load('results/rf_qtrait.Rdata')

library(tidyverse)
library(cowplot)
cbbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
                "#0072B2", "#D55E00", "#CC79A7", "#c5679b", "#be548f")
```

# Plot of simulation result, one time run

Require run `1_npdr_cc.Rmd`, `1_npdr_qtrait.Rmd`.

## Get the statistics:

```{r}
alpha <- 0.05
true.pos <- test_df_qtrait %>%
  filter((pval.adj < alpha) & functional) %>%
  nrow()
n.pos <- test_df_qtrait %>%
  filter((pval.adj < alpha)) %>%
  nrow()
(npdr.recall <- true.pos/(n.variables*pct.signals))
(npdr.precis <- true.pos/n.pos)

alpha <- 0.05
true.pos <- test_df_cc %>%
  filter((pval.adj < alpha) & functional) %>%
  nrow()
n.pos <- test_df_cc %>%
  filter((pval.adj < alpha)) %>%
  nrow()
(npdr.recall <- true.pos/(n.variables*pct.signals))
(npdr.precis <- true.pos/n.pos)
```


## Generate figure 1:

Set theme:

```{r}
plot_r2 <- function(x){
  x + geom_smooth(method = "lm", se = F, color = "grey") + 
  facet_wrap(~ method, scale = 'free') +
  geom_point(aes(colour = functional), alpha = 0.7, size = 2) +
  theme_bw() + theme(plot.title = element_text(hjust = 0.5)) + 
  scale_color_manual(values = cbbPalette[c(1,2)], labels = c('Non-functional', 'Functional')) +
  geom_text(cutoff_text, mapping = aes(x = x, y = y, label = label) , size = 4, color = cbbPalette[1]) + 
  geom_text(r2_text, mapping = aes(x = x, y = y, label = label), parse = T)
}
```

Now plot:

```{r}
# Continuous outcome:
qtrait_r <- merge(test_df_qtrait, rf_npdr_qtrait) %>%
  select(rrelief, beta.Z.att, functional, X.IncMSE) %>%
  rename(RRelief = rrelief, `Random forest` = X.IncMSE) %>%
  gather('method', 'imp_score', c(RRelief, `Random forest`))
qtrait_r$method <- factor(qtrait_r$method, levels = c('RRelief', 'Random forest'))
cc_r <- merge(test_df_cc, rf_npdr_cc) %>%
  select(rrelief, beta.Z.att, functional, MeanDecreaseAccuracy) %>%
  rename(`Relief-F` = rrelief, `Random forest` = MeanDecreaseAccuracy) %>%
  gather('method', 'imp_score', c(`Relief-F`, `Random forest`))
cc_r$method <- factor(cc_r$method, levels = c('Relief-F', 'Random forest'))


cutoff_text <- data.frame(
  label = rep('NPDR cutoff', 2), method = c('RRelief', 'Random forest'),
  x = c(0.25, 19), y = c(npdr.beta.cutoff.qtrait + 3, npdr.beta.cutoff.qtrait + 3))
r2_text <- data.frame(
  label = c(deparse(bquote(R^2 == .(r2_qtrait))), deparse(bquote(R^2 == .(r2_rf_qtrait)))),
  method = c('RRelief', 'Random forest'), x = c(0.25, 19), y = c(80, 80))
qtrait_plot <- ggplot(qtrait_r, aes(x = imp_score, y = beta.Z.att)) + 
  labs(x = NULL, title = 'Continuous outcome data with main effect', 
       y = bquote('NPDR linear'~beta), color = NULL) +
  geom_hline(yintercept = npdr.beta.cutoff.qtrait, linetype='dashed', alpha = 0.5)
qtrait_plot <- plot_r2(qtrait_plot) + theme(legend.position = c(0.63, 0.87), legend.margin = margin(c(1,1,1,1)))

# Dichotomous outcome:
cutoff_text <- data.frame(
  label = rep('NPDR cutoff', 2), method = c('Relief-F', 'Random forest'),
  x = c( 0.063, 4), y = c(npdr.beta.cutoff.cc + 1, npdr.beta.cutoff.cc + 1))
r2_text <- data.frame(
  label = c(deparse(bquote(R^2 == .(r2_cc))), deparse(bquote(R^2 == .(r2_rf_cc)))),
  method = c('Relief-F', 'Random forest'), x = c(0.062, 4) , y = c(24, 24))
cc_plot <- ggplot(cc_r, aes(x = imp_score, y = beta.Z.att)) + 
  labs(x = NULL, title = 'Dichotomous outcome data with interaction effect', 
       y = bquote('NPDR logistic'~beta), color = NULL) +
  geom_hline(yintercept=npdr.beta.cutoff.qtrait, linetype='dashed', alpha = 0.5)
cc_plot <- plot_r2(cc_plot) + theme(legend.position = c(0.63, 0.87), legend.margin = margin(c(1,1,1,1)))

 
fig1 <- plot_grid(qtrait_plot, cc_plot, nrow = 2, labels = 'AUTO')
ggsave(fig1, filename = 'figs/fig1.pdf', height = 7, width = 7)
```


## Generate figure 2:

```{r}
pr_qtrait <- prr_rf_qtrait %>%
  filter(type != 'NPDR') %>%
  rbind(prr_dat_qtrait) #%>% 

pr_cc <- prr_rf_cc %>% 
  filter(type != 'NPDR') %>%
  rbind(prr_dat_cc) #%>% 

relief_text <- data.frame(
  label = c(paste0('RRelief \n ', auprc_relief_qtrait), 
            paste0('Relief-F \n', auprc_relief_cc)),
  sim = c('Continuous outcome', 'Dichotomous outcome'),
  x = c(0.485 , 0.28), y = c(0.7, 0.91), type = c('Relief-F', 'Relief-F')
)

npdr_text <- data.frame(
  label = c(paste0('NPDR \n ', auprc_npdr_qtrait), 
            paste0('NPDR \n   ', auprc_npdr_cc)),
  sim = c('Continuous outcome', 'Dichotomous outcome'),
  x = c(0.755, 0.815), y = c(0.45, 0.88), type = c('NPDR', 'NPDR')
)

rf_text <- data.frame(
  label = c(paste0('Random forest \n', auprc_rf_qtrait), 
            paste0('Random forest \n', auprc_rf_cc)),
  sim = c('Continuous outcome', 'Dichotomous outcome'),
  x = c( 0.3, 0.65), y = c(0.2, 0.2), type = c('Random forest', 'Random forest')
)
colors <- viridis::viridis(n = 8)
pr <- rbind(pr_qtrait, pr_cc) %>% #data.frame() %>%
  mutate(sim = c(rep('Continuous outcome', nrow(pr_qtrait)), rep('Dichotomous outcome', nrow(pr_cc)))) %>%
  ggplot(aes(Recall, Precision, color = type)) +
  geom_path(size = 0.8) + theme_bw() +
  facet_wrap(~ sim) + 
  scale_color_manual(values = cbbPalette[c(8,3,6)]) +
  # scale_color_brewer(palette = 'Dark2') +
  # viridis::scale_color_viridis(discrete = T, option = 'B') +
  # scale_color_manual(values = colors[c(3,7, 5)]) + 
  scale_x_continuous(limits = c(0, 1.05), breaks = seq(0, 1.1, 0.2), labels = scales::percent) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2), labels = scales::percent) +
  geom_text(rf_text, mapping = aes(x = x, y = y, label = label), size = 3) +
  geom_text(npdr_text, mapping = aes(x = x, y = y, label = label), size = 3) +
  geom_text(relief_text, mapping = aes(x = x, y = y, label = label), size = 3) + 
  guides(color = FALSE)
pr

ggsave(pr, filename = 'figs/fig2_pr_plots.pdf', width = 6.2, height = 3)
```


## auROC for Supplement:

```{r}
ss_df <- rbind(ss_df_cc, ss_df_qtrait) %>%
  mutate(sim = rep(c('Dichotomous outcome', 'Continuous outcome'), each = nrow(ss_df_cc)))

npdr_text <- data.frame(
  label = c(paste0('NPDR \n AUC = ', auroc_npdr_cc), 
            paste0('NPDR \n AUC = ', auroc_npdr_qtrait)),
  sim = c('Dichotomous outcome', 'Continuous outcome'),
  x = c(0.77, 0.865), y = c(0.9, 0.95), type = c('NPDR', 'NPDR')
)

relief_text <- data.frame(
  label = c(paste0('Relief \n AUC = ', auroc_relief_cc), 
            paste0('Relief \n AUC = ', auroc_relief_qtrait)),
  sim = c('Dichotomous outcome', 'Continuous outcome'),
  x = c(0.77, 0.62), y = c(0.5, 0.5), type = c('Relief', 'Relief')
)

roc <- ggplot(ss_df, aes(x = Sensitivity, y = Specificity, color = type)) +   
  geom_path(size = 1) + theme_bw() + facet_wrap(~ sim) +
  scale_color_manual(values = cbbPalette[c(8,6)]) +
  scale_x_reverse(breaks = seq(1, 0, -0.2), labels = scales::percent) + 
  scale_y_continuous(breaks = seq(0, 1, 0.2), labels = scales::percent) + 
  geom_text(npdr_text, mapping = aes(x = x, y = y, label = label)) +
  geom_text(relief_text, mapping = aes(x = x, y = y, label = label)) +
  guides(color = FALSE)

roc
ggsave(roc, filename = 'figs/npdr_relief_auroc.pdf', height = 4 , width = 6)
```


## Compare NPDR and STIR:
Require run `1_npdr_cc.Rmd`.
```{r}
p <- ggplot(npdr_stir, aes(x=stir.log10,y=npdr.log10)) + 
  geom_smooth(method = 'lm', se = F, color = 'grey') + 
  geom_point(aes(colour = functional), alpha = 0.7, size = 3) +
  theme_bw() + theme(legend.position = c(0.78, 0.23)) +
  labs(colour = NULL, 
       x = bquote('STIR ('~-log[10]~'p'~')'), 
       y = bquote('NPDR ('~-log[10]~'p'~')'),
       title = NULL) + 
  annotate("text", x = 130, y = 130, label = deparse(bquote(R^2 > 0.99)), parse = T) +
  scale_color_manual(values = cbbPalette[c(1,2)],
                     labels = c('Non-functional', 'Functional')) +
  # viridis::scale_color_viridis(discrete = TRUE, 
  #                              labels = c('Non-functional', 'Functional')) + 
  geom_vline(xintercept=pcutoff, linetype='dashed', alpha = 0.5) +
  geom_hline(yintercept=pcutoff, linetype='dashed', alpha = 0.5)
p
ggsave(p, filename = paste0('figs/npdr_stir_p_cc.pdf'), height = 4.5, width = 4.5 )
```

# Replications of auPRC for Supplement:
Require run `2_npdr_relief_100_cc.Rmd`, `2_npdr_relief_100_qtrait.Rmd`.

```{r}
load('results/npdr_100_cc.Rdata')
pr_cc_100 <- pr_df

load('results/npdr_100_qtrait.Rdata')
pr_qtrait_100 <- pr_df

# pr_df
pr_df <- rbind(pr_cc_100, pr_qtrait_100) %>%
  mutate(sim = c(rep('Dichotomous outcome', nrow(pr_cc_100)), 
         rep('Continuous outcome', nrow(pr_qtrait_100)))) %>%
  mutate(newtype = as.factor(case_when((type %in% c('Relief-F', 'RRelief')) ~ 'Relief',
                             TRUE ~ as.character(type))))
pr_df$newtype <- factor(pr_df$newtype, levels = c('Relief', 'NPDR', 'Random forest'))

p_text <- data.frame(
  label = c('***', '***'),
  sim = c('Dichotomous outcome', 'Continuous outcome'),
  x = c(1.5, 1.5), y = c(0.52, 0.39), newtype =  c('NPDR', 'Relief')
)

p_text_2 <- data.frame(
  label = c('***', '***'),
  sim = c('Dichotomous outcome', 'Continuous outcome'),
  x = c(2.5, 2.5), y = c(0.52, 0.39), newtype =  c('NPDR', 'Relief')
)

pr_100 <- ggplot(pr_df, aes(x = newtype, y = aupr, fill = newtype, color = newtype)) + 
  geom_boxplot(alpha = 0.5, color = 'grey30', outlier.size = -1, width = 0.5) +
  labs(x = NULL, y = 'Area under the PR curve') + facet_wrap(~ sim, scales = 'free') +
  geom_jitter(height = 0, width = 0.1) +
  scale_color_manual(values = cbbPalette[c(6, 8, 3)]) +
  scale_fill_manual(values = cbbPalette[c(6, 8, 3)]) +
  geom_text(p_text, mapping = aes(x = x, y = y, label = label), color = 'grey20') +
  geom_text(p_text_2, mapping = aes(x = x, y = y, label = label), color = 'grey20') +
  # annotate("text", x = 1.5, y = 0.5, label = paste('p < 0.0001')) + 
  theme_bw() + guides(fill = F, color = F) 
pr_100

ggsave(pr_100, filename = paste0('figs/pr_compare_100.pdf'), height = 2.5, width = 5)
```

